GET {{hostname}}/pessoa

###

POST {{hostname}}/pessoa
Content-Type: application/json

{
  "nome": "Joao das Neves",
  "enderecoEmail": "joao@neves.com",
  "dataNascimento": "1981-01-01"
}

###

GET {{hostname}}/pessoa/asd
Accept: application/json